# Generated by Django 4.1 on 2022-09-22 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='book_cover',
            field=models.ImageField(height_field=2, upload_to='images/', width_field=1),
        ),
    ]
