# Generated by Django 4.1 on 2023-01-15 12:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0003_alter_book_book_cover'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='id',
            field=models.BigAutoField(auto_created=True, default=None, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='book',
            name='member_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='books', to='management.member'),
        ),
    ]
